# Generated by Django 4.0.4 on 2022-04-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
